import Link from "next/link";
import { ArrowLeft, ShieldCheck, Scale, Cookie } from "lucide-react";

export default function LegalPage() {
  return (
    <div className="mx-auto max-w-4xl px-6 py-20">
      {/* Back Button */}
      <Link
        href="/"
        className="mb-10 inline-flex items-center gap-2 text-sm text-stone-500 transition-colors hover:text-white"
      >
        <ArrowLeft size={16} />
        Back to Home
      </Link>

      <header className="mb-16">
        <h1 className="text-4xl font-bold tracking-tight text-white md:text-5xl">
          Legal Information
        </h1>
        <p className="mt-4 text-lg leading-relaxed text-stone-400">
          Last updated: April 2026. Transparent policies for a privacy-first
          quiz platform.
        </p>
      </header>

      <div className="space-y-20">
        {/* Privacy Policy Section */}
        <section id="privacy" className="scroll-mt-24">
          <div className="mb-6 flex items-center gap-3">
            <div className="rounded-lg bg-green-500/10 p-2 text-green-400">
              <ShieldCheck size={24} />
            </div>
            <h2 className="text-2xl font-bold text-white">Privacy Policy</h2>
          </div>
          <div className="space-y-4 leading-relaxed text-stone-400">
            <p>
              We believe in total privacy. Because this app features{" "}
              <strong className="text-stone-200">No Login</strong>, we do not
              collect, sell, or trade any personal identifiable information
              (PII).
            </p>
            <p>
              All your quiz data, scores, and history are stored exclusively in
              your browser&apos;s{" "}
              <strong className="text-stone-200">Local Storage</strong>. We have
              no access to this data.
            </p>
          </div>
        </section>

        {/* Terms of Service Section */}
        <section id="terms" className="scroll-mt-24">
          <div className="mb-6 flex items-center gap-3">
            <div className="rounded-lg bg-blue-500/10 p-2 text-blue-400">
              <Scale size={24} />
            </div>
            <h2 className="text-2xl font-bold text-white">Terms of Service</h2>
          </div>
          <div className="space-y-4 leading-relaxed text-stone-400">
            <p>
              By using QuizAI, you agree that the content generated by AI is for
              educational purposes. We strive for accuracy but are not
              responsible for any misleading information generated by the AI
              prompt system.
            </p>
            <p>
              You are free to use this tool for personal learning and interview
              preparation.
            </p>
          </div>
        </section>

        {/* Cookie Policy Section */}
        <section id="cookies" className="scroll-mt-24">
          <div className="mb-6 flex items-center gap-3">
            <div className="rounded-lg bg-amber-500/10 p-2 text-amber-400">
              <Cookie size={24} />
            </div>
            <h2 className="text-2xl font-bold text-white">Cookie Policy</h2>
          </div>
          <div className="space-y-4 leading-relaxed text-stone-400">
            <p>
              This site does not use tracking or advertising cookies. We only
              use <strong className="text-stone-200">Local Storage </strong> to
              persist your quiz results so you don&apos;t lose your progress
              when you refresh the page.
            </p>
          </div>
        </section>
      </div>

      {/* Footer Callout */}
      <div className="mt-20 border-t border-stone-800 pt-10 text-center">
        <p className="text-sm text-stone-500">
          Questions about these policies? Contact us via our GitHub repository.
        </p>
      </div>
    </div>
  );
}
