import QuestionProvider from "@/context/QuestionsContext";
import "./globals.css";

import NavBar from "@/components/ui/NavBar";
import QuizProvider from "@/context/QuizContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex min-h-full flex-col bg-[#0F172A] text-[#F1F5F9]">
        <QuizProvider>
          <QuestionProvider>
            <NavBar />
            {children}
          </QuestionProvider>
        </QuizProvider>
      </body>
    </html>
  );
}
