import QuestionProvider from "@/context/QuestionsContext";
import "./globals.css";

import NavBar from "@/components/ui/NavBar";
import QuizProvider from "@/context/QuizContext";
import Footer from "@/components/sections/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.jsx
export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="flex min-h-screen flex-col bg-stone-950 font-sans text-stone-100 antialiased">
        <QuizProvider>
          <QuestionProvider>
            <NavBar />
            {/* The main container should expand to fill remaining space */}
            <main className="flex-1">{children}</main>
            <Footer />
          </QuestionProvider>
        </QuizProvider>
      </body>
    </html>
  );
}
