export const initialQuestions = [
  {
    id: "1",
    quizId: "demo-quiz-1",
    question: "What is JavaScript?",
    options: [
      "Programming language",
      "Database",
      "Operating system",
      "Compiler",
    ],
    correctOption: 0,
  },
  {
    id: "2",
    quizId: "demo-quiz-1",
    question: "Which of these is a frontend framework?",
    options: ["Node.js", "React", "MongoDB", "Express"],
    correctOption: 1,
  },
  {
    id: "3",
    quizId: "demo-quiz-1",
    question: "What does HTML stand for?",
    options: [
      "Hyper Trainer Marking Language",
      "Hyper Text Markup Language",
      "Hyper Text Marketing Language",
      "Hyper Tool Multi Language",
    ],
    correctOption: 1,
  },
  {
    id: "4",
    quizId: "demo-quiz-1",
    question: "Which language is used for styling web pages?",
    options: ["HTML", "JQuery", "CSS", "XML"],
    correctOption: 2,
  },
  {
    id: "5",
    quizId: "demo-quiz-1",
    question: "Which is a backend runtime?",
    options: ["React", "Node.js", "CSS", "HTML"],
    correctOption: 1,
  },
  {
    id: "6",
    quizId: "demo-quiz-1",
    question: "Which database is NoSQL?",
    options: ["MySQL", "PostgreSQL", "MongoDB", "Oracle"],
    correctOption: 2,
  },
  {
    id: "7",
    quizId: "demo-quiz-1",
    question: "What is Next.js?",
    options: [
      "CSS framework",
      "React framework",
      "Database",
      "Programming language",
    ],
    correctOption: 1,
  },
  {
    id: "8",
    quizId: "demo-quiz-1",
    question: "Which keyword is used to declare a variable in JS?",
    options: ["int", "var", "string", "define"],
    correctOption: 1,
  },
  {
    id: "9",
    quizId: "demo-quiz-1",
    question: "Which method is used to print in console?",
    options: ["print()", "echo()", "console.log()", "write()"],
    correctOption: 2,
  },
  {
    id: "10",
    quizId: "demo-quiz-1",
    question: "Which symbol is used for comments in JS?",
    options: ["//", "<!-- -->", "#", "**"],
    correctOption: 0,
  },

  {
    id: "11",
    quizId: "cpp-quiz-1",
    question: "What is C++?",
    options: [
      "Object-Oriented Programming Language",
      "Database",
      "Operating System",
      "Markup Language",
    ],
    correctOption: 0,
  },
  {
    id: "12",
    quizId: "cpp-quiz-1",
    question: "Which symbol is used to include libraries?",
    options: ["#", "$", "@", "&"],
    correctOption: 0,
  },
  {
    id: "13",
    quizId: "cpp-quiz-1",
    question: "Which function is the entry point of a C++ program?",
    options: ["start()", "main()", "init()", "run()"],
    correctOption: 1,
  },
  {
    id: "14",
    quizId: "cpp-quiz-1",
    question: "Which keyword is used to define a class?",
    options: ["struct", "object", "class", "define"],
    correctOption: 2,
  },
  {
    id: "15",
    quizId: "cpp-quiz-1",
    question: "Which operator is used for scope resolution?",
    options: [".", "::", "->", "#"],
    correctOption: 1,
  },
  {
    id: "16",
    quizId: "cpp-quiz-1",
    question: "Which concept allows multiple functions with same name?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "Abstraction"],
    correctOption: 2,
  },
  {
    id: "17",
    quizId: "cpp-quiz-1",
    question: "Which of these is a loop in C++?",
    options: ["for", "repeat", "loop", "iterate"],
    correctOption: 0,
  },
  {
    id: "18",
    quizId: "cpp-quiz-1",
    question: "Which data type stores decimal values?",
    options: ["int", "char", "float", "bool"],
    correctOption: 2,
  },
  {
    id: "19",
    quizId: "cpp-quiz-1",
    question: "Which keyword is used for inheritance?",
    options: ["extends", "inherits", ":", "implements"],
    correctOption: 2,
  },
  {
    id: "20",
    quizId: "cpp-quiz-1",
    question: "Which header is used for input/output?",
    options: ["<stdio.h>", "<iostream>", "<conio.h>", "<math.h>"],
    correctOption: 1,
  },
  {
    id: "1",
    quizId: "web-dev-hard-1",
    question: "Which of the following selectors has the highest specificity?",
    options: [
      "nav ul li:nth-child(2) a",
      ".main-nav #login-btn",
      "div.header.active > p",
      "html body main div.content",
    ],
    correctOption: 1,
  },
  {
    id: "2",
    quizId: "web-dev-hard-1",
    question:
      "In the CSS Box Model, if an element has 'box-sizing: border-box', what is included in the defined width?",
    options: [
      "Content only",
      "Content + Padding",
      "Content + Padding + Border",
      "Content + Padding + Border + Margin",
    ],
    correctOption: 2,
  },
  {
    id: "3",
    quizId: "web-dev-hard-1",
    question:
      "Which HTML5 element is used to provide a caption for a <figure> element?",
    options: ["<legend>", "<caption>", "<figcaption>", "<label>"],
    correctOption: 2,
  },
  {
    id: "4",
    quizId: "web-dev-hard-1",
    question: "What is the result of setting 'flex-shrink: 0' on a flex item?",
    options: [
      "The item will not grow beyond its basis",
      "The item will maintain its size even if the container narrows",
      "The item will disappear if space is restricted",
      "The item will fill all remaining space",
    ],
    correctOption: 1,
  },
  {
    id: "5",
    quizId: "web-dev-hard-1",
    question:
      "Which CSS property is required to make 'z-index' effective on a non-static element?",
    options: ["display", "float", "position", "overflow"],
    correctOption: 2,
  },
  {
    id: "6",
    quizId: "web-dev-hard-1",
    question: "In CSS Grid, what does the 'fr' unit represent?",
    options: [
      "A fixed pixel ratio",
      "A fraction of the free space in the grid container",
      "The font-relative size of the track",
      "A percentage of the viewport width",
    ],
    correctOption: 1,
  },
  {
    id: "7",
    quizId: "web-dev-hard-1",
    question:
      "Which attribute is used to specify that an <iframe> should load its content only when it is scrolled near?",
    options: [
      'lazyload="true"',
      'loading="lazy"',
      'defer="async"',
      'fetch="low"',
    ],
    correctOption: 1,
  },
  {
    id: "8",
    quizId: "web-dev-hard-1",
    question: "What is the default value of the 'position' property in CSS?",
    options: ["relative", "absolute", "fixed", "static"],
    correctOption: 3,
  },
  {
    id: "9",
    quizId: "web-dev-hard-1",
    question:
      "Which pseudo-class matches an element only if it has no children (including text nodes)?",
    options: [":void", ":no-child", ":empty", ":blank"],
    correctOption: 2,
  },
  {
    id: "10",
    quizId: "web-dev-hard-1",
    question:
      "How does the 'async' attribute differ from 'defer' when loading external scripts?",
    options: [
      "Async runs only after the DOM is fully parsed",
      "Async pauses HTML parsing to execute the script immediately after it downloads",
      "Defer blocks the DOM construction while downloading",
      "There is no difference in modern browsers",
    ],
    correctOption: 1,
  },
  {
    id: "11",
    quizId: "web-dev-hard-1",
    question:
      "Which of the following is NOT a valid value for the 'display' property?",
    options: ["inline-flex", "grid-area", "contents", "flow-root"],
    correctOption: 1,
  },
  {
    id: "12",
    quizId: "web-dev-hard-1",
    question:
      "What is the purpose of the 'rel=\"noopener\"' attribute on an <a> tag?",
    options: [
      "To improve SEO rankings",
      "To prevent the new page from accessing the window.opener object",
      "To ensure the link opens in a new tab",
      "To allow the destination to track the referrer",
    ],
    correctOption: 1,
  },
  {
    id: "13",
    quizId: "web-dev-hard-1",
    question:
      "Which CSS function allows you to perform calculations to determine property values?",
    options: ["eval()", "compute()", "calc()", "var()"],
    correctOption: 2,
  },
  {
    id: "14",
    quizId: "web-dev-hard-1",
    question:
      "In the context of CSS Variables, what is the correct syntax to provide a fallback value?",
    options: [
      "var(--main-color, #000)",
      "var(--main-color | #000)",
      "var(--main-color || #000)",
      "var(--main-color); fallback: #000;",
    ],
    correctOption: 0,
  },
  {
    id: "15",
    quizId: "web-dev-hard-1",
    question:
      "Which HTML attribute is used to define the character encoding for the document?",
    options: [
      '<meta charset="UTF-8">',
      '<meta encoding="UTF-8">',
      '<head type="UTF-8">',
      '<script charset="UTF-8">',
    ],
    correctOption: 0,
  },
];

export const initialQuiz = [
  {
    id: "demo-quiz-1",
    title: "Demo Quiz",
    difficulty: "easy",
    status: true,
  },
  {
    id: "cpp-quiz-1",
    title: "Cpp",
    difficulty: "easy",
    status: false,
  },
  {
    id: "web-dev-hard-1",
    title: "Web Dev (Html-Css)",
    difficulty: "hard",
    status: true,
  },
];
